version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - app_store:/workspace/app/node_modules
    command: >
      sh -c 
        "yarn && tail -f /dev/null"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_ROOT_USER: docker
      MYSQL_DATABASE: mydb
      TZ: 'Asia/Tokyo'
    volumes:
      - db_store:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_store:
  app_store: